### ISSUE TITLE
Is this plugin used to only update the 'pod' image?

### ISSUE THREAD

**Issue by MorrisMatrix** [josmo/drone-k8s-deployment#1]
Is this plugin used to only update the 'pod' image on the Kubernetes deployment or can you also update the deployment configuration in Kubernetes, such as environment variables and # of replicas?

**Comment by josmo** [comment]
Currently just the pod, would be easy to add more options  though :)

**Comment by MorrisMatrix** [comment]
Do you plan to add more options?

**Comment by josmo** [comment]
I can if there's specific asks and also will totally take prs
