### ISSUE TITLE
date_label example usage

### ISSUE THREAD

**Issue by lnikell** [josmo/drone-k8s-deployment#2]
Hi, could you please provide the example usage of data_label. I suppose that you assume to use it as a hack for force upgrade of a container. I'm just thinking maybe better for this case will be to just have an option such as "force: true" which will add label by default without extra configuration.

**Comment by josmo** [comment]
@lnikell it's should be renamed to date_annotation_key. Basically it allows you to give it a key for the annotation and have that set to whatever to give it ie. 
...
  date_label: ${DRONE_BUILD_CREATED}

I thought about making it be a force: true however then you have less control on how it works and would force some type of annotation on you :/ . If you have a good alternative feel free to PR in and I'll take it.  Right now I'm using the drone-helm plugin and the drone-k8s-job more then the deployment one. :)

**Comment by josmo** [comment]
yeah this just allows you to decide what the annotation should be ie.

date_label: deployment.drone.io/date-deployed

I'm down if you want to add a PR. It is there to force the container to upgrade if you're delpoying latest.
